
/**************************************************************
 *	
 *	turn, 8 bit, 11025Hz,
 *	1 channel, 6624 bytes/channel
 *	Total Size: 1 * 6624 + 4 (header) = 6668 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/dodo/cs2261/milestone04/turn.wav
 *	Time-stamp: Wed Nov 28 11:43:20 2018
 *	
 **************************************************************/

#ifndef __TURNH__
#define __TURNH__

#define TURNFREQ 11025
#define TURNLEN 6624

extern const unsigned char turn[6624];

#endif /* __TURNH__ */
