
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 195382 bytes/channel
 *	Total Size: 1 * 195382 + 4 (header) = 195426 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/dodo/cs2261/lab10/Lab10_Sound/GameSong.wav
 *	Time-stamp: Tue Nov 13 14:28:14 2018
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 195382

extern const unsigned char GameSong[195382];

#endif /* __GAMESONGH__ */
