
/**************************************************************
 *	
 *	space03, 8 bit, 11025Hz,
 *	1 channel, 8352 bytes/channel
 *	Total Size: 1 * 8352 + 4 (header) = 8396 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/KartikKini/Downloads/PC Computer - Portal 2 - Space Sphere/sounds/space03.wav
 *	Time-stamp: Tue Nov 03 22:03:48 2015
 *	
 **************************************************************/

#ifndef __SPACE03H__
#define __SPACE03H__

#define SPACE03FREQ 11025
#define SPACE03LEN 8352

extern const unsigned char space03[8352];
extern int _space03len;

#endif /* __SPACE03H__ */
