
/**************************************************************
 *	
 *	space06, 8 bit, 11025Hz,
 *	1 channel, 68832 bytes/channel
 *	Total Size: 1 * 68832 + 4 (header) = 68876 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/KartikKini/Downloads/PC Computer - Portal 2 - Space Sphere/sounds/space06.wav
 *	Time-stamp: Tue Nov 03 22:04:24 2015
 *	
 **************************************************************/

#ifndef __SPACE06H__
#define __SPACE06H__

#define SPACE06FREQ 11025
#define SPACE06LEN 68832

extern const unsigned char space06[68832];
extern int _space06len;

#endif /* __SPACE06H__ */
