
/**************************************************************
 *	
 *	space01, 8 bit, 11025Hz,
 *	1 channel, 44928 bytes/channel
 *	Total Size: 1 * 44928 + 4 (header) = 44972 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/KartikKini/Downloads/PC Computer - Portal 2 - Space Sphere/sounds/space01.wav
 *	Time-stamp: Tue Nov 03 22:03:37 2015
 *	
 **************************************************************/

#ifndef __SPACE01H__
#define __SPACE01H__

#define SPACE01FREQ 11025
#define SPACE01LEN 44928

extern const unsigned char space01[44928];
extern int _space01len;

#endif /* __SPACE01H__ */
