
/**************************************************************
 *	
 *	space04, 8 bit, 11025Hz,
 *	1 channel, 5472 bytes/channel
 *	Total Size: 1 * 5472 + 4 (header) = 5516 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/KartikKini/Downloads/PC Computer - Portal 2 - Space Sphere/sounds/space04.wav
 *	Time-stamp: Tue Nov 03 22:03:54 2015
 *	
 **************************************************************/

#ifndef __SPACE04H__
#define __SPACE04H__

#define SPACE04FREQ 11025
#define SPACE04LEN 5472

extern const unsigned char space04[5472];
extern int _space04len;

#endif /* __SPACE04H__ */
