
/**************************************************************
 *	
 *	space07, 8 bit, 11025Hz,
 *	1 channel, 8640 bytes/channel
 *	Total Size: 1 * 8640 + 4 (header) = 8684 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/KartikKini/Downloads/PC Computer - Portal 2 - Space Sphere/sounds/space07.wav
 *	Time-stamp: Tue Nov 03 22:04:32 2015
 *	
 **************************************************************/

#ifndef __SPACE07H__
#define __SPACE07H__

#define SPACE07FREQ 11025
#define SPACE07LEN 8640

extern const unsigned char space07[8640];
extern int _space07len;

#endif /* __SPACE07H__ */
