
/**************************************************************
 *	
 *	space02, 8 bit, 11025Hz,
 *	1 channel, 20160 bytes/channel
 *	Total Size: 1 * 20160 + 4 (header) = 20204 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/KartikKini/Downloads/PC Computer - Portal 2 - Space Sphere/sounds/space02.wav
 *	Time-stamp: Tue Nov 03 22:03:43 2015
 *	
 **************************************************************/

#ifndef __SPACE02H__
#define __SPACE02H__

#define SPACE02FREQ 11025
#define SPACE02LEN 20160

extern const unsigned char space02[20160];
extern int _space02len;

#endif /* __SPACE02H__ */
