
/**************************************************************
 *	
 *	space05, 8 bit, 11025Hz,
 *	1 channel, 25632 bytes/channel
 *	Total Size: 1 * 25632 + 4 (header) = 25676 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/KartikKini/Downloads/PC Computer - Portal 2 - Space Sphere/sounds/space05.wav
 *	Time-stamp: Tue Nov 03 22:04:06 2015
 *	
 **************************************************************/

#ifndef __SPACE05H__
#define __SPACE05H__

#define SPACE05FREQ 11025
#define SPACE05LEN 25632

extern const unsigned char space05[25632];
extern int _space05len;

#endif /* __SPACE05H__ */
