
/**************************************************************
 *	
 *	StartSFX, 8 bit, 11025Hz,
 *	1 channel, 127584 bytes/channel
 *	Total Size: 1 * 127584 + 4 (header) = 127628 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/dodo/cs2261/lab10/Lab10_Sound/StartSFX.wav
 *	Time-stamp: Tue Nov 13 14:30:25 2018
 *	
 **************************************************************/

#ifndef __STARTSFXH__
#define __STARTSFXH__

#define STARTSFXFREQ 11025
#define STARTSFXLEN 127584

extern const unsigned char StartSFX[127584];

#endif /* __STARTSFXH__ */
