
/**************************************************************
 *	
 *	TitleSong, 8 bit, 11025Hz,
 *	1 channel, 447027 bytes/channel
 *	Total Size: 1 * 447027 + 4 (header) = 447071 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/dodo/cs2261/lab10/Lab10_Sound/TitleSong.wav
 *	Time-stamp: Tue Nov 13 14:30:45 2018
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 447027

extern const unsigned char TitleSong[447027];

#endif /* __TITLESONGH__ */
