
/**************************************************************
 *	
 *	crash, 8 bit, 11025Hz,
 *	1 channel, 12096 bytes/channel
 *	Total Size: 1 * 12096 + 4 (header) = 12140 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/dodo/cs2261/milestone04/crash.wav
 *	Time-stamp: Wed Nov 28 11:42:47 2018
 *	
 **************************************************************/

#ifndef __CRASHH__
#define __CRASHH__

#define CRASHFREQ 11025
#define CRASHLEN 12096

extern const unsigned char crashSound[12096];

#endif /* __CRASHH__ */
