
/**************************************************************
 *	
 *	soundtrack, 8 bit, 11025Hz,
 *	1 channel, 1153766 bytes/channel
 *	Total Size: 1 * 1153766 + 4 (header) = 1153810 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/dodo/cs2261/milestone04/soundtrack.wav
 *	Time-stamp: Wed Nov 28 11:43:42 2018
 *	
 **************************************************************/

#ifndef __SOUNDTRACKH__
#define __SOUNDTRACKH__

#define SOUNDTRACKFREQ 11025
#define SOUNDTRACKLEN 1153766

extern const unsigned char soundtrack[1153766];

#endif /* __SOUNDTRACKH__ */
